### PR TITLE
Changing project to a simple easy_login app and adding setuptools.

### PR DESCRIPTION
**Pull request by yuriiZherebukh**
…t and leaving easy_login app

### CODE REVIEW

**Review by KIVIDARK — APPROVED** [review]

**Comment by Oleh-Hrebchuk** [comment]
you deleted developments files.
we should create a package on only for easy login folder but we also should leave files for development.

**Comment by Oleh-Hrebchuk** [comment]
also, we should add docs folders for future

**Comment by yuriiZherebukh** [comment]
> you deleted developments files.
> we should create a package on only for easy login folder but we also should leave files for development.

Yes, of course. We can leave this changes on 1-easy-login-package branch and create for example another branch for development.

**Comment by Oleh-Hrebchuk** [comment]
please do rebase and fix confilcts

**Pull request closed without merging**
